GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZUBleGFtcGxlLmNvbSIsIm5iZiI6MTYxNDY1MDk2Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Im1uLWpkYmMtYXV0aCIsImxhbmd1YWdlIjoiZW4iLCJleHAiOjE2MTQ2NTQ1NjYsImlhdCI6MTYxNDY1MDk2NiwiaGFpcl9jb2xvciI6ImJyb3duIn0.qFf7q5P91jHuAu6vY-NgPd8ewAV36QsseO30rOUbRCs